import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
 import Tour from "@/component/tour";
import Contact from "@/component/contact/contact";
import SideBarDashboard from "@/component/sidebar/sidebar";
 
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Login Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        
<script src="https://cdn.jsdelivr.net/npm/driver.js@1.0.1/dist/driver.js.iife.js"></script>
<link rel="stylesheet" href="https://unpkg.com/driver.js/dist/driver.min.css"/>

      </Head>
      <main >
      <div id="viewport">
      <SideBarDashboard/>       <Tour/>

     <Contact/>
</div>      
       </main>
    </>
  );
}
