import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useSelector, useDispatch } from 'react-redux';
 import { useRouter } from 'next/router';
import { useEffect } from 'react';
import axios from "axios";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const router = useRouter();

  const dispatch = useDispatch();
  const user = useSelector((state) => state.user);

  useEffect(() => {
    router.push('/projet');

  }, []);


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
      <div className="flex items-center justify-center min-h-screen bg-gray-100">
    
    <img src="bannertaskmanager.jpg" alt="" srcset=""className="img-fluid"/>
    </div>
    
      </main>
    </>
  );
}
